name: CI/CD Pipeline

defaults:
  run:
    working-directory: auto-deploy

on:
  push:
    branches: [main]
jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Start JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: mvn clean install
      - run: mv target/auto-deploy-0.0.1-SNAPSHOT.jar auto-deploy-0.0.1-SNAPSHOT.jar
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Deploy to S3
        run: aws s3 sync target/auto-deploy-0.0.1-SNAPSHOT.jar s3://test-artifact-bucket-sean --delete
